# Generated by Django 5.1.1 on 2024-09-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_get_latest_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None, help_text="Name of subscription", max_length=255
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Any notes or other information about the subscription",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Subscription cost",
                        max_digits=10,
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=12, help_text="Number of times per year amount is paid"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Show the subscription in the active subscriptions list",
                    ),
                ),
                (
                    "exclude",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude subscription from overview and aggregations",
                    ),
                ),
                (
                    "opened_on",
                    models.DateField(
                        blank=True,
                        help_text="Date the subscription was opened",
                        null=True,
                    ),
                ),
                (
                    "closed_on",
                    models.DateField(
                        blank=True,
                        help_text="Date the subscription was closed",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="User defined order for display",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ("order", "-opened_on"),
                "get_latest_by": "opened_on",
            },
        ),
        migrations.AlterField(
            model_name="budget",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="year",
            field=models.PositiveSmallIntegerField(
                default=2024, help_text="Household fiscal year", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
