dist: xenial
language: python
python: "3.9"

addons:
  postgresql: "10"

install:
  - pip install -r requirements.txt

services:
  - postgresql

env:
  global:
    - DATABASE_URL="postgres://postgres@localhost:5432/ledger_test"

script: pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - benjamin@bengfort.com
    on_success: change
    on_failure: always
