# Generated by Django 3.0.2 on 2020-02-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_rename_returns_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxreturn',
            options={'get_latest_by': 'year', 'ordering': ('-year',)},
        ),
    ]
