# Generated by Django 5.1.1 on 2024-09-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0003_get_latest_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxreturn",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
