# Generated by Django 2.0.5 on 2018-06-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mark_transaction_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exclude',
            field=models.BooleanField(default=False, help_text='Exclude account from overview and aggregations'),
        ),
    ]
