# Generated by Django 2.2.2 on 2019-06-24 14:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='memo',
            field=models.CharField(blank=True, help_text='A short memo or note describing the balance sheet', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', help_text='Short description for the payment', max_length=255)),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly'), ('F', 'Infrequent')], default='M', help_text='The frequency of the payment', max_length=1)),
                ('day', models.PositiveSmallIntegerField(blank=True, default=None, help_text='Day of week, month, quarter, or year the payment occurs on', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(366)])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='The default amount of the recurring payment', max_digits=10, null=True)),
                ('active', models.BooleanField(default=True, help_text='Show the payment in the active payments list')),
                ('credit', models.ForeignKey(help_text='The source of funds for the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_sources', to='accounts.Account')),
                ('debit', models.ForeignKey(help_text='The destination of funds for the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.Account')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ('debit__name', 'description'),
            },
        ),
    ]
