# Generated by Django 3.0.5 on 2020-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Ca', 'Cash'), ('Cc', 'Credit Card'), ('Ln', 'Loan'), ('Iv', 'Investment'), ('Is', 'Insurance'), ('Bl', 'Billing'), ('Dn', 'Charitable')], default='Ca', help_text='The account type for related accounts', max_length=2),
        ),
    ]
